CREATE TRIGGER fed_customer_his_move_INSERT
  AFTER INSERT ON fed_customer
    FOR EACH ROW BEGIN

INSERT INTO local_customer
VALUES (
NEW.customerId,
NEW.resellerId,
NEW.accountId,
NEW.companyName,
NEW.partnerAgentId,
NEW.phone,
NEW.fax,
NEW.email,
NEW.billingEmail,
NEW.techEmail,
NEW.ccNumber,
NEW.ccType,
NEW.ccExpireDate,
NEW.ccNameOnCard,
NEW.perMinuteRate,
NEW.perMinuteRateTollFree,
NEW.meetMeRate,
NEW.billingAddressId,
NEW.shippingAddressId,
NEW.taxJurisdictionId,
NEW.anniversaryDate,
NEW.paymentMethodId,
NEW.maxPaths,
NEW.statusId,
NEW.salesRepId,
NEW.planType,
NEW.originalActivationDate,
NEW.cancellationDate,
NEW.note ,
NEW.hostedFaxEnabled,
NEW.hostedFaxTermsApproved,
NEW.hostedFaxSenders,
NEW.hostedFaxPerPageRate,
NEW.timezone,
NEW.dashboard_subscriptions,
NEW.due_date_offset,
NEW.dunning_emails_disabled,
NEW.dunning_charge_disabled,
NEW.networkToolEnabled,
NEW.ccProfileId,
NEW.defaultCCPaymentProfileId,
NEW.referring_organization_id,
NEW.invoice_download_expiration,
NEW.siteAddressUpdateFailed,
NEW.lastSiteAddressUpdateDate,
NEW.siteAddressId,
NEW.externalAccountId,
now(),
now()
);
END


CREATE TRIGGER fed_customer_his_move_UPDATE
  AFTER UPDATE ON fed_customer
    FOR EACH ROW BEGIN
UPDATE local_customer SET
OLD.customerId = NEW.customerId,
OLD.resellerId = NEW.resellerId,
OLD.accountId = NEW.accountId,
OLD.companyName = NEW.companyName,
OLD.partnerAgentId = NEW.partnerAgentId,
OLD.phone = NEW.phone,
OLD.fax = NEW.fax,
OLD.email = NEW.email,
OLD.billingEmail = NEW.billingEmail,
OLD.techEmail = NEW.techEmail,
OLD.ccNumber = NEW.ccNumber,
OLD.ccType = NEW.ccType,
OLD.ccExpireDate = NEW.ccExpireDate,
OLD.ccNameOnCard = NEW.ccNameOnCard,
OLD.perMinuteRate = NEW.perMinuteRate,
OLD.perMinuteRateTollFree = NEW.perMinuteRateTollFree,
OLD.meetMeRate = NEW.meetMeRate,
OLD.billingAddressId = NEW.billingAddressId,
OLD.shippingAddressId = NEW.shippingAddressId,
OLD.taxJurisdictionId = NEW.taxJurisdictionId,
OLD.anniversaryDate = NEW.anniversaryDate,
OLD.paymentMethodId = NEW.paymentMethodId,
OLD.maxPaths = NEW.maxPaths,
OLD.statusId = NEW.statusId,
OLD.salesRepId = NEW.salesRepId,
OLD.planType = NEW.planType,
OLD.originalActivationDate = NEW.originalActivationDate,
OLD.cancellationDate = NEW.cancellationDate,
OLD.note  = NEW.note,
OLD.hostedFaxEnabled = NEW.hostedFaxEnabled,
OLD.hostedFaxTermsApproved = NEW.hostedFaxTermsApproved,
OLD.hostedFaxSenders = NEW.hostedFaxSenders,
OLD.hostedFaxPerPageRate = NEW.hostedFaxPerPageRate,
OLD.timezone = NEW.timezone,
OLD.dashboard_subscriptions = NEW.dashboard_subscriptions,
OLD.due_date_offset = NEW.due_date_offset,
OLD.dunning_emails_disabled = NEW.dunning_emails_disabled,
OLD.dunning_charge_disabled = NEW.dunning_charge_disabled,
OLD.networkToolEnabled = NEW.networkToolEnabled,
OLD.ccProfileId = NEW.ccProfileId,
OLD.defaultCCPaymentProfileId = NEW.defaultCCPaymentProfileId,
OLD.referring_organization_id = NEW.referring_organization_id,
OLD.invoice_download_expiration = NEW.invoice_download_expiration,
OLD.siteAddressUpdateFailed = NEW.siteAddressUpdateFailed,
OLD.lastSiteAddressUpdateDate = NEW.lastSiteAddressUpdateDate,
OLD.siteAddressId = NEW.siteAddressId,
OLD.externalAccountId = NEW.externalAccountId,
modified_at = now();

END